import { STORAGE_KEY, PALETTE, FLOAT_TOLERANCE } from "./constants.js";

// ── Formatting ────────────────────────────────────────────────────────────────

/** Format decimal hours as a human-readable string, e.g. 1.5 → "1h 30m" */
export function formatHours(h) {
  const totalMinutes = Math.round(h * 60);
  const hours   = Math.floor(totalMinutes / 60);
  const minutes = totalMinutes % 60;
  if (hours   === 0) return `${minutes}m`;
  if (minutes === 0) return `${hours}h`;
  return `${hours}h ${minutes}m`;
}

/** Snap hours to the nearest step (in minutes). */
export function snapToStep(hours, stepMinutes) {
  return Math.round(hours * 60 / stepMinutes) * stepMinutes / 60;
}

// ── localStorage ──────────────────────────────────────────────────────────────

/** Read and parse persisted state. Returns null on failure. */
export function loadState() {
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    return raw ? JSON.parse(raw) : null;
  } catch {
    return null;
  }
}

/** Persist state to localStorage. Silently ignores errors. */
export function saveState(state) {
  try {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(state));
  } catch {}
}

// ── Data migration ────────────────────────────────────────────────────────────

/** One-time migration from legacy versioned keys to the current key. */
export function migrateOldData() {
  const OLD_KEYS = ["sliders_v5", "sliders_v4", "sliders_v3", "sliders_v2", "sliders_v1"];
  try {
    if (localStorage.getItem(STORAGE_KEY)) return;
    for (const oldKey of OLD_KEYS) {
      const data = localStorage.getItem(oldKey);
      if (data) { localStorage.setItem(STORAGE_KEY, data); break; }
    }
  } catch {}
}

// ── Task scaling ──────────────────────────────────────────────────────────────

/**
 * Shrink-only scaling: compress tasks proportionally when the day window shrinks
 * below the sum of task hours. If the window is larger, tasks are left untouched.
 */
export function scaleTasksToTotal(tasks, targetTotal) {
  if (tasks.length === 0) return tasks;
  const currentSum = tasks.reduce((sum, t) => sum + (t.hours || 0), 0);

  // Window fits all tasks — leave them alone
  if (targetTotal >= currentSum - FLOAT_TOLERANCE) return tasks;
  if (currentSum <= 0) return tasks;

  // Window too small — shrink proportionally
  const targetMinutes = Math.round(targetTotal * 60);
  let assigned = 0;
  const newMinutes = tasks.map((t, i) => {
    if (i === tasks.length - 1) return Math.max(0, targetMinutes - assigned);
    const m = Math.round((t.hours || 0) / currentSum * targetMinutes);
    assigned += m;
    return m;
  });
  return tasks.map((t, i) => ({ ...t, hours: Math.max(0, newMinutes[i] / 60) }));
}

// ── Markdown import / export ──────────────────────────────────────────────────

/** Parse a previously exported markdown file back into tasks + day window. */
export function parseMD(text) {
  const tasks = [];
  let dayStart = null, dayEnd = null;

  for (const line of text.split("\n")) {
    const dayMatch = line.match(/^> Day: (\d+(?:\.\d+)?):(\d+) → (\d+(?:\.\d+)?):(\d+)/);
    if (dayMatch) {
      dayStart = parseInt(dayMatch[1]) + (dayMatch[2] === "30" ? 0.5 : 0);
      dayEnd   = parseInt(dayMatch[3]) + (dayMatch[4] === "30" ? 0.5 : 0);
    }

    const taskMatch = line.match(/^## (.+?) \[(\d+(?:\.\d+)?)h\] (#[0-9a-fA-F]{6})?/);
    if (taskMatch) {
      tasks.push({
        id:            Date.now() + Math.random(),
        name:          taskMatch[1].trim(),
        hours:         parseFloat(taskMatch[2]),
        originalHours: parseFloat(taskMatch[2]),
        color:         taskMatch[3] || PALETTE[tasks.length % PALETTE.length],
        locked:        false,
        actual:        0,
      });
    }
  }
  return { tasks, dayStart, dayEnd };
}

/** Serialize current state to a markdown string for export. */
export function serializeMD(tasks, dayStart = 0, dayEnd = 24) {
  const dayLength  = dayEnd - dayStart;
  const total      = tasks.reduce((s, t) => s + t.hours, 0);
  const unallocated = Math.max(0, dayLength - total);

  const pad = n => String(n).padStart(2, "0");
  const toTime = h => `${pad(Math.floor(h))}:${h % 1 ? "30" : "00"}`;

  let out = `# Sliders — Daily Time Allocation\n\n`;
  out += `> Day: ${toTime(dayStart)} → ${toTime(dayEnd)} (${formatHours(dayLength)})\n`;
  out += `> Total: ${formatHours(total)} / ${formatHours(dayLength)} | Unallocated: ${formatHours(unallocated)}\n\n---\n\n`;

  for (const t of tasks) {
    const pctStr = dayLength > 0 ? ((t.hours / dayLength) * 100).toFixed(1) : "—";
    out += `## ${t.name} [${t.hours.toFixed(4)}h] ${t.color}\n`;
    out += `- Planned: ${formatHours(t.hours)} (${pctStr}%)\n`;
    out += `- Actual: ${formatHours(t.actual || 0)}\n\n`;
  }

  return out + `---\n_Generated by Sliders App_\n`;
}

// ── Colour helpers ────────────────────────────────────────────────────────────

function hexToHsl(hex) {
  let r = parseInt(hex.slice(1, 3), 16) / 255;
  let g = parseInt(hex.slice(3, 5), 16) / 255;
  let b = parseInt(hex.slice(5, 7), 16) / 255;
  const max = Math.max(r, g, b), min = Math.min(r, g, b);
  let h, s, l = (max + min) / 2;
  if (max === min) {
    h = s = 0;
  } else {
    const d = max - min;
    s = l > 0.5 ? d / (2 - max - min) : d / (max + min);
    switch (max) {
      case r: h = ((g - b) / d + (g < b ? 6 : 0)) / 6; break;
      case g: h = ((b - r) / d + 2) / 6; break;
      default: h = ((r - g) / d + 4) / 6;
    }
  }
  return [h * 360, s * 100, l * 100];
}

function hslToHex(h, s, l) {
  s /= 100; l /= 100;
  const k = n => (n + h / 30) % 12;
  const a = s * Math.min(l, 1 - l);
  const f = n => l - a * Math.max(-1, Math.min(k(n) - 3, Math.min(9 - k(n), 1)));
  return "#" + [f(0), f(8), f(4)].map(x => Math.round(x * 255).toString(16).padStart(2, "0")).join("");
}

/** Adjust a hex colour's lightness and optionally saturation. */
export function adjustColor(hex, lightnessDelta, saturationDelta = 0) {
  if (!hex || !hex.startsWith("#") || hex.length < 7) return hex;
  try {
    const [h, s, l] = hexToHsl(hex);
    return hslToHex(
      h,
      Math.max(0, Math.min(100, s + saturationDelta)),
      Math.max(0, Math.min(100, l + lightnessDelta)),
    );
  } catch {
    return hex;
  }
}
